name: Deploy to Vercel

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Vercel
        uses: vercel/actions@v1
        with:
          token: waGphFvwrJqCDSrHG8j5c4zt
          project-id: prj_oUWOgWHTUtrnAIoU7OckowFlUZBv
          production: ${{ github.ref == 'refs/heads/main' }}
